(def guess ((o tries 1) (o r (rand 100)))
  (when (< tries 10)
    (pr "your guess: ")
    (let y (read)
      (prn)
      (if (is y r)
          (do (prn "yay")                  
              (pr "you got it in " tries " tries."))
          (do (prn y " is too " (if (< y r) "low" "high"))
              (guess (+ tries 1) r))))))
